#!/usr/bin/env bash
# configures an Ubuntu machine with nginx
FILE="/etc/nginx/sites-available/default"
ERRORFILE="/usr/share/nginx/html/404error.html"

REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}\n"
ERRORREDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
CUSTOMHEADER='\n\tadd_header X-Served-By $hostname;\n'

# Update package lists and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Append lines to the Nginx configuration file
sudo sed -i "/location \/ {/a\\$REDIRECT" "$FILE"
sudo sed -i "/location \/ {/a\\$ERRORREDIRECT" "$FILE"
sudo sed -i "/location \/ {/a\\$CUSTOMHEADER" "$FILE"

# Restart Nginx
sudo service nginx restart
