#!/usr/bin/env bash
# shellcheck disable=SC2009
# Use 'ps' command to list all processes and grep for 'bash'
ps aux --forest | grep -i 'bash' | grep -v 'grep' | while read -r line; do
    echo "$line"
done
