#!/usr/bin/env bash
#Bash script that displays the PID, along with the process name
for pid_dir in /proc/[0-9]*/; do
    pid=$(basename "$pid_dir")

    if [[ -e "$pid_dir/cmdline" ]]; then
        process_name=$(tr -d '\0' < "$pid_dir/cmdline")

        process_name=$(basename "$process_name")

        if [[ "$process_name" == *"bash"* ]]; then
            echo "$pid   $process_name"
        fi
    fi
done
