#!/usr/bin/env bash
#Bash script that stops 4-to_infinity_and_beyond process.
process_name="4-to_infinity_and_beyond"
pid=$(pgrep -o "$process_name")

if [ -z "$pid" ]; then
    echo "Process '$process_name' not found."
else
    kill "$pid"
    echo "Stopped process '$process_name' with PID $pid."
fi
