#!/usr/bin/env bash
#Bash script that displays To infinity and beyond indefinitely
trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond indefinitely"
    sleep 2
done
