#!/usr/bin/env bash

# Initialize a count
count=1

# Use a while loop to loop from 1 to 10
while [ $count -le 10 ]
do
  # Check for specific loop iterations
  if [ $count -eq 4 ]; then
    echo "bad luck"
  elif [ $count -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  
  # Increment the count
  ((count++))
done
